<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34892" started-at="2017-11-29T01:38:48Z" finished-at="2017-11-29T01:39:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34892" started-at="2017-11-29T01:38:48Z" finished-at="2017-11-29T01:39:23Z">
      <class name="OrderManagement.OMxiangqingTest">
        <test-method status="PASS" signature="addListener(org.testng.ITestContext)[pri:0, instance:OrderManagement.OMxiangqingTest@6767c1fc]" name="addListener" is-config="true" duration-ms="15" started-at="2017-11-29T09:38:48Z" finished-at="2017-11-29T09:38:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@4b20ca2b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addListener -->
        <test-method status="PASS" signature="doBeforeMethod()[pri:0, instance:OrderManagement.OMxiangqingTest@6767c1fc]" name="doBeforeMethod" is-config="true" duration-ms="6142" started-at="2017-11-29T09:38:48Z" finished-at="2017-11-29T09:38:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeMethod -->
        <test-method status="PASS" signature="testBackLogin()[pri:0, instance:OrderManagement.OMxiangqingTest@6767c1fc]" name="testBackLogin" duration-ms="11609" started-at="2017-11-29T09:38:54Z" finished-at="2017-11-29T09:39:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBackLogin -->
        <test-method status="FAIL" signature="xq()[pri:0, instance:OrderManagement.OMxiangqingTest@6767c1fc]" name="xq" duration-ms="16334" started-at="2017-11-29T09:39:06Z" depends-on-methods="OrderManagement.OMxiangqingTest.testBackLogin" finished-at="2017-11-29T09:39:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at OrderManagement.OMxiangqingTest.xq(OMxiangqingTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- xq -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:OrderManagement.OMxiangqingTest@6767c1fc]" name="doAfterMethod" is-config="true" duration-ms="772" started-at="2017-11-29T09:39:22Z" finished-at="2017-11-29T09:39:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- OrderManagement.OMxiangqingTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
